### ISSUE TITLE
Dashboard Not Redirecting

### ISSUE THREAD

**Issue by 7mTo** [ajamjoom/tamerny#6]
Latest that worked was this commit [https://github.com/7mTo/tamerny/commit/e03a90d6c1c49a77aabb6b58e3d51e450231a5ab](url)

I still am digging for what the cause is and I suspect that it is a package. I installed:

- babel-runtime.
- moyasar.
- bycript.
- request.
- meteor-node-stubs.
- cls-bluebird

**Comment by 7mTo** [comment]
All packages are exactly matching with no change, so that goes out of the way.

I will try to check the additions one by one until I pinpoint the problem.

**Comment by 7mTo** [comment]
It works now. Thanks @ajamjoom . If you want to add a notice on what happened than go ahead or close it. I'll leave it to you.

**Comment by ajamjoom** [comment]
When an operator is initially created, a document in the pairing collection is added with that operator's ID. Each Pairing document should have an opertorID string along with a string array of userIds. However, when the pairing document is created for the first time the userIds object field is not created because the operator will not be initially serving anyone. So this created an issue in accessing the dashboard page because the data retrieved from the dashboard page is contingent on checking the userIds field in pairings... if it's not existant then that page completely doesn't work.
